import React from 'react'
import { Link } from 'react-router-dom'

import { StyledContent, Heading, FullSection } from '../../styles/PageStyles'

export const Privacy = () => {
  return (
    <FullSection style={{ display: "flex", alignItems: "center" }}>
      <StyledContent>
        <Heading>
          <h1>Privacy Policy</h1>
        </Heading>
        <p><Link to="/">RapGuide.com</Link> is operated by <strong>Rap Guide Media LLC</strong>, a company wholly-owned and operated by <a href="https://www.bababrinkman.com" target="_blank" rel="noopener noreferrer">Baba Brinkman</a>.</p>

        <p>We collect data from students and teachers for the purpose of providing online lessons and displaying and analyzing the aggregate, anonymous numerical results and outcomes of these lessons, for the purpose of academic research and for improving the function of <Link to="/">RapGuide.com</Link>.</p>

        <p>No data collected from students and teachers in the completion of an online lesson will be sold to any third parties for any reason, or shared with any third parties for any reason other than academic research or to improve the function of <Link to="/">RapGuide.com</Link>. Furthermore, no personal data collected will be displayed publicly on the site without the consent of the student and/or teacher, or the parent or guardian of the student if the student is a minor. If the appropriate permissions are granted, content generated by students, such as annotations, may be displayed publicly either with anonymous attribution or pseudonyms or last names concealed. Content generated by teachers will likewise be made available to other teachers and displayed publicly on the site only if consent is explicitly granted.</p>

        <p>We also collect data from public users of the site who submit requests for new Rap Guides and/or submit comments and upvotes on existing lessons, requests and annotations. By submitting this content and interacting with the site, you are consenting to have your submissions displayed publicly and linked to your account, with the user information displayed that you have selected in your account dashboard.</p>

        <p>This site and it's operations are very new, so this privacy policy will be subject to update as activities warrant.</p>

        <p><strong>Privacy policy most recently updated:</strong> <em>September 9th, 2020</em></p>
      </StyledContent>
    </FullSection>
  )
}

export default Privacy;

